security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        in_memory:
            memory:
                users:
                    arash:
                        password: test
                        roles: [ 'ROLE_USER' ]
                    root:
                        password: root
                        roles: [ 'ROLE_ADMIN' ]

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        # login:
        #     pattern:  ^/demo/secured/login$
        #     security: false

        secured_area:
            pattern:    ^/
            anonymous: ~

            form_login:
                login_path: /login
                check_path: /login/check

            logout:
                path: /logout
                target: /

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ROLE_USER}
